### ISSUE TITLE
Use other wikis

### ISSUE THREAD

**Issue by Skilld18** [Skilld18/grok#2]
Use the full media wiki api and access other wikis

**Comment by Skilld18** [comment]
This partially works but you have to hardcode the wiki api. There should be a better solution.

**Comment by the-replicat** [comment]
Working on adding a -o/--other flag to allow the use of the last sys.argv as wiki url.

Will be making a pull request tonight, school's proxy is blocking any pull/clone from command line

**Comment by Skilld18** [comment]
Pull request approved. Fixed a minor issue where the flags got unset.
